### ISSUE TITLE
Install instructions not working

### ISSUE THREAD

**Issue by logc** [zheli/layer-scala-lsp#1]
I was trying to install this layer on my Spacemacs (0.300.0, `develop` branch, on Emacs 26.2).

Following the instructions, adding this to my `.spacemacs`, in `dotspacemacs-configuration-layers`:

```elisp
(scala-lsp :location
          (recipe :fetcher github
                  :repo "zheli/layer-scala-lsp"))
```

gives me this warning on restart (or reload):

```console
Warning: Unknown layer scala-lsp declared in dotfile.
```

Reading [this issue on Spacemacs](https://github.com/syl20bnr/spacemacs/issues/10494), it looks like external layers are not supported. Maybe the instructions mean to put the layer in `dotspacemacs-additional-packages`? I know for a fact that Github recipes work there ...

**Comment by zheli** [comment]
My bad, I have a symbolic link in my `.emacs.d/private` folder so I thought the github fetcher worked...

You can try to clone this repo inside `.emacs.d/private` folder instead and then simpily add `scala-lsp` into your `dotspacemacs-configuration-layers` list.

Also it's worth mentioning that I haven't tried it with the spacemacs develop branch yet, let me if it works :)

**Comment by zheli** [comment]
Close issue due to inactivity.
