### ISSUE TITLE
Dot completion

### ISSUE THREAD

**Issue by kaaninho** [zheli/layer-scala-lsp#2]
Hi,

thanks for the layer btw. I got it working and it shows function arguments etc. 
But I miss dot completion, does this work on your system? 
(with "dot completion" I mean accessing available fields/methods of an object like `myObj.head`)

**Comment by zheli** [comment]
Yes, it works on my machine™ 😄 
Sometimes that happened to me if the project failed to compile. You need to have at least one successful compilation I think. What does it say in your `.metals/metals.log`?

**Comment by kaaninho** [comment]
Thank you, the pointer to `.metals/metals.log` was helpful. Something didn't compile, as you suggested. Now it works. Very nice!
